### ISSUE TITLE
Evaluating on older CPUs

### ISSUE THREAD

**Issue by ntadej** [catboost/catboost#1009]
Problem: Evaluation C++ library crashes with illegal instruction
catboost version: 0.17.3
Operating System: CentOS 7
CPU: AMD Opteron(tm) Processor 2431
Flags from `/proc/cpuinfo`:
```
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save pausefilter
```

Tried building with `ya make` and clang directly on another host with slightly newer AMD CPU.

**Comment by kizill** [comment]
I found only some kind of monkey-patching solutions for building for such and old platforms - one is patching https://github.com/catboost/catboost/blob/master/build/ymake.core.conf#L3318
replacing 
```
SSE_DEFINES=-DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSSE3_ENABLED=1
SSE4_DEFINES=-DSSE41_ENABLED=1 -DSSE42_ENABLED=1 -DPOPCNT_ENABLED=1 -DCX16_ENABLED=1
...
SSE_CFLAGS=$SSE2_CFLAGS $SSE3_CFLAGS $SSSE3_CFLAGS
SSE4_CFLAGS=$SSE41_CFLAGS $SSE42_CFLAGS $POPCNT_CFLAGS $CX16_FLAGS
```
with
```
SSE_DEFINES=-DSSE_ENABLED=1
SSE4_DEFINES=-DPOPCNT_ENABLED=1 -DCX16_ENABLED=1
...
SSE_CFLAGS=$SSE2_CFLAGS $SSE3_CFLAGS $SSSE3_CFLAGS
SSE4_CFLAGS=$POPCNT_CFLAGS $CX16_FLAGS
```
and then build all needed targets.

**Comment by kizill** [comment]
Did you try to use this hack?

**Comment by ntadej** [comment]
I tried and it did not seem to help...

**Comment by kizill** [comment]
Fixed by @ntadej in PR https://github.com/catboost/catboost/pull/1030

**Comment by VanessaE** [comment]
Sorry to necro-post, but this package as supplied by the repositories that `pip` pulls from on Debian "Bullseye", is still broken.  I guess what you're interested is the package version and name, which is `catboost-0.25.1-cp39-none-manylinux1_x86_64.whl`.  My CPU Phenom II X6 1055T, if that's of use.
