### ISSUE TITLE
CatBoostRegressor's training results on GPU and CPU are very different. How to beat this?

### ISSUE THREAD

**Issue by Mangol31** [catboost/catboost#1408]
Faced with the fact that the results of CatBoostRegressor on the GPU are significantly worse than on the CPU. How do I fix this problem? What parameters should I pay attention to? I tried to "twist" different parameters, but I didn't achieve success. I understand that the question is quite frequent. But I haven't been able to find an answer yet.

Problem:
catboost version:
Operating System:
CPU:
# GPU:

**Comment by bakwc** [comment]
Try to compare output of `get_all_params()`. I had similar issue, for me difference was in `Newton` vs `Gradient` leaf_estimation_method.

**Comment by yellowdolphin** [comment]
Same observation. I tried to use all the same params for both CPU/GPU, without success. The GPU fit does not reproduce the CPU one and is consistently inferior. [Here ](https://www.kaggle.com/greendolphin/catboost-gpu-issue) is a kaggle notebook for demonstration (catboost 0.24.1).

**Comment by ellehoej** [comment]
+1, same observation here. GPU fit is significantly inferior in my case (eg. R^2 from 0.76 to 0.45). The CPU fit looks similar to the GPU fit in the release I updated from (0.14.2).

**Comment by kizill** [comment]
Thank you all for examples! We will investigate this behaviour to track it's origin and will return with some fix, I hope :)

**Comment by DeanLeeFumu** [comment]
Same here, tried tons of params still didn't help. Hope there will be new update soon. Thanks!

**Comment by DeanLeeFumu** [comment]
I manage to recreate the similar result by setting boarder_count and fold_permuntation_block as CPU's.

Got better result by setting **FeatureFreq's CtrBorderCount** in **combinations_ctr** and **simple_ctr** from **Median** to **Uniform** .

But changing **combinations_ctr** and **simple_ctr** will cause training result randomly different despite specified constant seed.

**Comment by humcasma** [comment]
I also get very bad results with GPU and default parameters, compared to CPU. If I modify the parameters so that they match the CPU ones (except for _combinations_ctr_ and _simple_ctr_), I get an improvement in performance, but it is still lower than with CPU. Changing _FeatureFreq_ as suggested by @DeanLeeFumu did not work. 

Can we still get equal or higher performance with GPU if parameters are tuned, or is GPU performance always going to be worse?

**Comment by RiverShah** [comment]
For all numeric features, it should be trivial to switch between CPU and GPU. Having to discover and change parameters for GPU tuning seems extra steps prone to human / code error. But even normalising for CPU / GPU parameter retains a big quality gap. 
```
# X is all numeric
model_cpu = CatBoostRegressor(bootstrap_type="Bernoulli", task_type='CPU')
model_cpu.fit(X, y)
model_gpu = CatBoostRegressor(bootstrap_type="Bernoulli", task_type='GPU')
model_gpu.fit(X, y)
# These two models should give near equivalent performance. Please try datasets from KDD, Kaggle or synthetic.
```
GPU performance is significantly worse over CPU baselines and requesting we increase priority to fix this. Catboost is by far the best boosting library and having the GPU speed working properly is an essential feature. Linking other issues here: #1257 #1313

**Comment by kizill** [comment]
Sorry for long wait. I'll start to investigate this issue in nearest time.

**Comment by user673** [comment]
@kizill, are there any updates about this issue?

**Comment by sumankgunnala** [comment]
@kizill, Greatly appreciate any update on this issue or workaround that can be used... for my data set with combination of numerical and categorical, exact same run has no comparison in results... Metrics at inference time are very bad the moment I use GPU training.. learn and test error convergence during training looks good

**Comment by HongshengFang** [comment]
Same issue here. Trained on GPU for dataset with both categorical and numerical features. Results significantlly wrose then task_type = CPU, although runtime is much better. Any fixes yet？

**Comment by qo4on** [comment]
How do you work in Yandex, only on CPU? More than half a year have passed but the issue in such a crucial thing is still here.

**Comment by GabrielFo** [comment]
> Same issue here. Trained on GPU for a dataset with both categorical and numerical features. Results are significantly worse than task_type = CPU, although runtime is much better. Any fixes yet？

+1 here, results are significantly worse with GPU.

**Comment by BeomyoungKim** [comment]
I Saw that this issue is Implemented in v0.25 
"Support exact leaf values estimation on GPU for MAE, MAPE, Quantile"
Can I find any related explanation ? If not, can you explain what it means? 
@LyzhinIvan

**Comment by LyzhinIvan** [comment]
> I Saw that this issue is Implemented in v0.25
> "Support exact leaf values estimation on GPU for MAE, MAPE, Quantile"
> Can I find any related explanation ? If not, can you explain what it means?
> @LyzhinIvan

Hi, @BeomyoungKim!
This issue is not related to the implemented exact estimation method for MAE etc.
This issue is corresponding to significant underperform on GPU comparing to CPU with same training parameters on almost all loss functions.
Exact method is about another issue. Before v0.25 training on GPU with MAE, MAPE and Quantile was very slow in terms of convergence (loss decreases very slowly) because of absence of exact leaf estimation method on GPU. Now it is implemented and training with MAE on GPU and CPU are very similar.

**Comment by BeomyoungKim** [comment]
Thanks @LyzhinIvan !
I thought this issue was related to 'exact leaf values ~' because of the above tag (https://github.com/catboost/catboost/issues/1408#issuecomment-749659814)

**Comment by pxpwoa** [comment]
same issue on classifier. The result of CPU is significantly better than CPU's.

**Comment by jonimatix** [comment]
Is there a solution to fix the gap between CPU and GPU training performance?

**Comment by robcaulk** [comment]
Same issue here, not using any categorical features.

**Comment by AlexanderKUA** [comment]
Same issue for me, accuracy loss is huge.

Model params:
```
model = cbt.CatBoostRegressor(objective='Tweedie:variance_power=1.5', min_data_in_leaf=20, verbose=0, task_type='GPU', border_count=254, random_seed=1)
```

I tried to set border_count as mentioned above without success. 
I tried call get_all_params() but got following error:
```
CatBoostError: catboost/private/libs/options/plain_options_helper.cpp:921: data_processing_options: key embedding_processing_options wasn't added to plain options.
```

**Comment by ThomasWolf0701** [comment]
Is this still the case in version 1.0.3 ? Or has this been fixed in the meantime ?

**Comment by eskayML** [comment]
The issue still seems to be there , my f1 score drops significantly when I set task_type = "GPU"  ,  although I still enjoy the speed of training at which GPU executes , but performance is quite important

**Comment by icejean** [comment]
Is there any progress in this issue? I can verify the accelation with classification mentioned in this article:
[10x Times Faster CatBoost Training Speed with an NVIDIA GPU](https://towardsdatascience.com/10x-times-fast-catboost-training-speed-with-an-nvidia-gpu-5ffefd9b57a6), but the issue with CatBoostRegressor is also experienced as mentioned above.

Best regards.

**Comment by profgandhi** [comment]
I get significantly less accurate results. Is there a solution to this?

**Comment by KruASe76** [comment]
three years passed... the issue is still there
using CatBoostRegressor the learn loss is 0.9999970 after 600 iterations on GPU

**Comment by fengshansi** [comment]
I found that default param are different on cpu and gpu. Also, some param can only work on cpu.

**Comment by JacobLiu-S** [comment]
I've tried tuning both GPU and CPU params for the same train/val/test data using optuna (100 trials), the results of CPU seems way better that GPU. Finally I give up. I guess, the performance drop mainly come from bootstrap type. Because in CPU, the default in my problem is Bayesian with subsample, while subsample < 1 and Bayesian is not supported in GPU at the same time. But when I switch to Bernuli or Possion, the performance is significantly worse.

**Comment by Fredrik-C** [comment]
I also experience much worse quality when training on GPU (speed is however ~x10 times faster).
Even if I try with the same values for border_count and use bootstrap_type = Bayesian by using colsample_bylevel = 1 the difference in quality is huge.

CatBoost is great, but if the GPU training quality issue cant be resolved I think it would be better to deprecate (or trigger a warning) GPU support since this might damage the experience with CatBoost.
