### ISSUE TITLE
CatboostRegressor.score() not working when training with RMSEWithUncertainty

### ISSUE THREAD

**Issue by humcasma** [catboost/catboost#1482]
Problem:
When training with _RMSEWithUncertainty_  loss,  `_predict()` returns a two-dimensional array. This provokes  `CatboostRegressor.score()` to fail with an exception:

> /usr/local/lib/python3.6/dist-packages/catboost/core.py in score(self, X, y)
>       4969         )
>       4970         total_sum_of_squares = np.sum((y - y.mean(axis=0)) ** 2)
> -> 4971         residual_sum_of_squares = np.sum((y - predictions) ** 2)
>       4972         return 1 - residual_sum_of_squares / total_sum_of_squares
>       
> ValueError: operands could not be broadcast together with shapes (1685,) (1685,2) 

Because of this, CatboostRegressor cannot be used with Scikit-learn's cross-validation utilities if no scoring function is explicitly specified. If a scikit-learn scoring function is specified, a similar error will happen when running the scoring function.
A simple solution seems to be to let the `predict()` method return only the mean when using `prediction_type='RawFormulaVal'` and return mean and variance when using `prediction_type='RMSEWithUncertainty'`. Note that this would also eliminate the confusing behavior that exists now. Currently, _RawFormulaVal_ seems to return the log of the standard deviation, while _RMSEWithUncertainty_ seems to return the variance.

catboost version: 0.24.2, CPU

**Comment by LyzhinIvan** [comment]
Fixed by commit https://github.com/catboost/catboost/commit/741c2cf683d509e01b3453d79a36bd1cf3657a0b.

**Comment by humcasma** [comment]
Thanks for the commit.
Note, however, that the provided fix only solves part of the problem (the one related to `CatboostRegressor.score()`), but it does not solve the problem when using other scoring functions with scikit-learn. E.g., if I want to use `sklearn.model_selection.cross_validate` with `CatboostRegressor` and `scoring='neg_mean_abosulte_error'`, an exception will be raised, because scikit-learn expects `CatboostRegressor.predict()` to return a one-dimensional array.

**Comment by LyzhinIvan** [comment]
We are not going to change this behavior. But you can use simple wrapper class for these cases:
```
class Wrapper(CatBoostRegressor):
    def predict(self, *args, **kwargs):
        return super().predict(*args, **kwargs)[:, 0]
```
