### ISSUE TITLE
[PySpark 3.x.y compatibility] cannot import name 'JavaPredictionModel' from 'pyspark.ml.util'

### ISSUE THREAD

**Issue by andrey-khropov** [catboost/catboost#1600]
Catboost_spark version: 0.25-rc3.

Incompatible with pyspark 3.x.y because JavaPredictionModel class has been removed from pyspark.ml.util.

**Comment by andrey-khropov** [comment]
Fixed in r0.25

**Comment by tinder-arozinov** [comment]
I'm still encountering this issue, even in the Maven release 0.25, specifically `catboost-spark_3.0_2.12:0.25`. E.g. after doing `import catboost_spark` I get:

`ImportError: cannot import name 'JavaClassificationModel' from 'pyspark.ml.classification'`

I'm running this on Spark 3.1.1.

**Comment by zankorobov** [comment]
I'm having the same issue, I think. I've installed the latest catboost-spark_3.0_2.12:025 on a databricks cluster, but can't run 'import catboos_spark': "cannot import name 'JavaClassificationModel' from 'pyspark.ml.classification'"

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@andrey-khropov Could you please have a look?

**Comment by praateekmahajan** [comment]
I know the plan is to support only 3.0, but in case the plan is to move to 3.1, this issue might come up again in a different form.
In pyspark 3.1.x I they moved `JavaClassificationModel` to `ClassificationModel` in [SPARK-29212](https://issues.apache.org/jira/browse/SPARK-29212) and also introduced `_JavaClassificationModel`, which breaks the code for Spark 3.1 again.

**Comment by andrey-khropov** [comment]
Spark 3.1 is supported from release 1.0.3. There should be no error if a package with the appropriate Spark version is used.

**Comment by kevingriest** [comment]
@andrey-khropov I am still running into a similar error with release 1.0.4 when trying to install on Spark/Pyspark 3.1.2. Instead of complaining about JavaClassificationModel, it throws the following ImportError:

ImportError: cannot import name 'JavaProbabilisticClassificationModel' from 'pyspark.ml.classification'

 I also tried installing the 1.0.3 and 0.25 CatBoost releases instead but faced the same problem.
