### ISSUE TITLE
Problem with ScikitLearn 1.01 SelectFromModel and column names when using catboost

### ISSUE THREAD

**Issue by ThomasWolf0701** [catboost/catboost#1949]
Problem:  catboost does not work properly with the SelectFromModel function in scikit 1.01 as it seems to delete column names,
making the return get_feature_names_out not return proper column names. This leads to additional proplems when combining catboost and Scikit Learn in a pipeline and caching during hyperparameter optimization. For other models it works well.
catboost version: 1.03
Operating System: Wimdows

Here is an reproducible example :

from sklearn.svm import LinearSVR
from sklearn.datasets import load_iris
from catboost import  CatBoostRegressor
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectFromModel

##################################################
#get the data and assign column names
##################################################

iris = load_iris()
X = pd.DataFrame(data= np.c_[iris['data']])
X.columns = ["a","b","c","d"]
y = iris.target

##########################################################
##test with catboost
##########################################################

#train the selector
selector = SelectFromModel(estimator=CatBoostRegressor())
selector.fit(X, y)
#show the selected columns
selector.get_feature_names_out()
#array(['x2', 'x3'], dtype=object) instead of "b" and "c"
#the oroginal column names have been replaced with x2 and x3

#if the selector is applied
selector.transform(X.iloc[1:2,:])
#I get the following warning
#X has feature names, but SelectFromModel was fitted without feature names

##############################################################
##Now the same with SVR, here it works
##############################################################

#train the selector
selector = SelectFromModel(estimator=LinearSVR())
selector.fit(X, y)

#the proper names are being returned
selector.get_feature_names_out()
#array(['d'], dtype=object) and "d" is a proper column name

#apply the selector
selector.transform(X.iloc[1:2,:])
#no warning is given

##############################################################################
##The error from hyperparameter tuning, caching and SelectFromModel. This worked well before scikit 1.00
##And occurs when a SelectFromModel Transformer is loaded from cache.
###############################################################################

File "C:\LocalTools\Miniconda\envs\my-rdkit-env\lib\site-packages\sklearn\pipeline.py", line 647, in transform
    Xt = transform.transform(Xt)
  File "C:\LocalTools\Miniconda\envs\my-rdkit-env\lib\site-packages\sklearn\feature_selection\_base.py", line 83, in transform
    X = self._validate_data(
  File "C:\LocalTools\Miniconda\envs\my-rdkit-env\lib\site-packages\sklearn\base.py", line 580, in _validate_data
    self._check_n_features(X, reset=reset)
  File "C:\LocalTools\Miniconda\envs\my-rdkit-env\lib\site-packages\sklearn\base.py", line 395, in _check_n_features
    raise ValueError(
ValueError: X has 290 features, but SelectFromModel is expecting 0 features as input.

**Comment by ThomasWolf0701** [comment]
https://github.com/scikit-learn/scikit-learn/issues/21949#issuecomment-991370528 This answer from the scikit-learn github adresses the problem.

**Comment by glemaitre** [comment]
The problem should be fixed in release 1.0.2 in scikit-learn.

**Comment by ThomasWolf0701** [comment]
Even if it now runs with 1.0.2 there is still a problem with Catboost not supporting the way scikit passes column names. Categorial variables have to be defined via column names, but the matrix itself, which is passed to catboost does not have column names. So if catboost would  support the scikit way of passing column names in a scikit learn pipeline the usage of categorial features would become much easier.

**Comment by glemaitre** [comment]
> Even if it now runs with 1.0.2 there is still a problem with Catboost not supporting the way scikit passes column names. Categorial variables have to be defined via column names, but the matrix itself, which is passed to catboost does not have column names. So if catboost would support the scikit way of passing column names in a scikit learn pipeline the usage of categorial features would become much easier.

Just to be sure, @ThomasWolf0701 you should not get an error in 1.0.2 but a warning instead?

**Comment by ThomasWolf0701** [comment]
@glemaitre it´s still crashing with ValueError: X has 290 features, but SelectFromModel is expecting 0 features as input.
