### ISSUE TITLE
error with max_leaves option on specified max_leaves value

### ISSUE THREAD

**Issue by BoKS-man** [catboost/catboost#849]
Problem: error with max_leaves option on specified max_leaves value
catboost version: 0.14.2
Operating System: Windows 10 Pro 64-bit (10.0, Build 17134) (17134.rs4_release.180410-1804)
CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
GPU: NVIDIA GeForce GTX 1080 Ti

i have an next error: "CatBoostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/libs/options/catboost_options.cpp:530: max_leaves option works only with lossguide tree growing has occured on training".
this error occurs only when i'm searching parameters with hyperopt and the  max_leaves parameter value equals to 31.0

here example of parameters: 
{'boosting_type': 'Plain', 'depth': 5, 'eval_metric': 'RMSE', 'gpu_ram_part': 0.15, 'l2_leaf_reg': 5.0, 'learning_rate': 0.01432370314082507, 'loss_function': 'RMSE', 'max_bin': 64, 'max_leaves': 31.0, 'min_data_in_leaf': 5.0, 'randem_seed': 42, 'task_type': 'GPU', 'thread_count': -1}

there is a code example:

params = {
	'eval_metric': 'RMSE',
	'loss_function': 'RMSE',
	'boosting_type': 'Plain',
	'thread_count': -1,
	'learning_rate': hp.loguniform('learning_rate', -5.0, -2.3),
	'depth': hp.choice('depth', np.arange(1, 14, dtype=int)),
	'min_data_in_leaf': hp.quniform ('min_data_in_leaf', 1, 6, 1),
	'max_leaves': hp.quniform ('max_leaves', 10, 200, 1),
	'l2_leaf_reg': hyperopt.hp.quniform('l2_leaf_reg', 1, 7, 1),
	'max_bin': 64,
	'task_type': 'GPU',
	'random_seed': 42,
	'gpu_ram_part': .15
}
model = catboost.train(pool = _train,
					   params = params,
					   eval_set = _val,
					   iterations = num_rounds,
					   early_stopping_rounds = early_stopping,
					   verbose = False)
y_pred = model.predict(X_test)

**Comment by annaveronika** [comment]
The error msg explains the problem - these parameters (max_leaves and min_data_in_leaf) are for a different growing policy - for LossGuide. Which is not the default one. And it is not set in parameters.

**Comment by annaveronika** [comment]
Can you try 0.15 and see if other values of max_leaves don't produce the error?

**Comment by annaveronika** [comment]
Sorry, I was not clear. Can you please update CatBoost to version 0.15?

**Comment by annaveronika** [comment]
I hope your issue is solved. Closing because of inactivity.

**Comment by rohan-gt** [comment]
@annaveronika this is still an issue in CatBoost v0.24. Is there a way to ignore max_leaves in growing policies other than LossGuide?

**Comment by LyzhinIvan** [comment]
> @annaveronika this is still an issue in CatBoost v0.24. Is there a way to ignore max_leaves in growing policies other than LossGuide?

Hi, @rohan-gt !

There are several parameters in CatBoost that are meaningful only for specific values of other parameter. We will not ignore such inconsistencies. So, raising an error in such case is the expected behavior.

**Comment by rohan-gt** [comment]
@LyzhinIvan wouldn't a warning suffice? This becomes a problem because it breaks execution while performing hyperparameter tuning

**Comment by leedrake5** [comment]
This appears to be an issue with multiple parameters (e.g. `_catboost.CatBoostError: catboost/private/libs/options/bootstrap_options.cpp:23: Error: you shoudn't provide bootstrap options if bootstrap is disabled
`). I understand the philosophy that flagging useless variables is important - but parameter searching means these stumbling blocks will show up over and over again. I'd recommend a "parameter search" boolean that would bypass these errors and allow parameterization to do its thing.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @leedrake5 ✋ 
many thanks for using catboost 😍 

i think it is the grid searcher that should react to such exceptions

silently ignoring (one of? some of?? all of???) conflicting options is ambiguous

**Comment by leedrake5** [comment]
Hi @Evgueni-Petrov-aka-espetrov, many thanks for the response and attention to the issue. This approach is used in peer libraries. An example is XGBoost. When grid searching parameters for it, I can use "gbtree", "gblinear", or "dart" as boosters. Each has arguments unique to it - for example "dart" requires arguments like "drop_rate" that are irrelevant, but not harmful, to the "gblinear" booster. If passed, they are just ignored and the algorithm carries on. 

This means I can set up an efficient grid search to find the best model architecture for my data across different model structures. 

With catboost I can't, unless I want to wrap many "if else" statements across a tremendous amount of code, working error to error as they emerge. If an argument is given that can just be ignored because of another setting, that would allow me as a researcher to explore the data in a comparable way to other gradient boosters. 

This can be taken too far - for example errors should be raised if a GPU-specific feature is passed to a CPU model (e.g. "Armijilo"). But if the training function could just disregard irrelevant arguments passed (or disregard + warn) that would make it much easier for me to incorporate catboost into my research, and increase the chances that I can find relationships in my data by exploring a wide parameter space.

**Comment by akshat-suwalka-dream11** [comment]
I am unable to find the solution for above error.
I am using 'quantile' as loss_function and recieveing the same error as above.
Do catBoost do not have any solution yet?
