### ISSUE TITLE
 shap does not work

### ISSUE THREAD

**Issue by sonfiree** [catboost/catboost#910]
```
shap.initjs()
explainer = shap.TreeExplainer(model)
```
Error
`CatBoostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/libs/model/json_model_helpers.cpp:410: can't parse params file`

shap version: 0.29.3
catboost version: 0.15.2
Operating System: windows 10
CPU: i7 8700
GPU: 1060 6GB

**Comment by ek-ak** [comment]
Hi! Can you provide representative example or share model?

**Comment by sonfiree** [comment]
> Привет! Можете ли вы привести типичный пример или поделиться моделью?

from catboost import CatBoostClassifier

model = CatBoostClassifier(
    iterations=1000000,
    early_stopping_rounds=1000,
    random_seed=42,
    learning_rate=0.6,
    custom_loss=['AUC', 'Accuracy', 'F1'],
    use_best_model=True,
    l2_leaf_reg=3,
    bagging_temperature=1,
    random_strength=10,
    task_type = "GPU"
)

**Comment by sadiqquasem** [comment]
Check this out:

`https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/Catboost%20tutorial.ipynb`

**Comment by sonfiree** [comment]
@sadiqquasem ?

**Comment by lupusomniator** [comment]
Hi, i've tried to reproduce this error, but it didn't work out. 
```python
import shap
import catboost
import pandas as pd

print('Cat is:', catboost.__version__)
print('Pandas is:', pd.__version__)
print('Shap is:', shap.__version__)

features = dict()
features['CAT_FEATURE'] = ['1','1','1','1','1','1','0','0']
features['FLOAT_FEATURE'] = [1, 1, 1, 1, 1, 1, 0, 0]
features['TARGET'] = [1, 1, 1, 1, 1, 0, 0, 0]

pool = catboost.Pool(
    list(zip(features['CAT_FEATURE'], features['FLOAT_FEATURE'])),
    features['TARGET'],
    cat_features=[0]
)

model = catboost.CatBoostClassifier(
    iterations=100,
    early_stopping_rounds=1000,
    random_seed=42,
    learning_rate=0.6,
    custom_loss=['AUC', 'Accuracy', 'F1'],
    l2_leaf_reg=3,
    bagging_temperature=1,
    random_strength=10,
    task_type = "GPU",
    silent=True
)
model.fit(pool)
shap.initjs()
explainer = shap.TreeExplainer(model)
```
I get this error:
```
~/miniconda3/envs/lew_conda/lib/python3.7/site-packages/shap/explainers/tree.py in get_trees(self, data, data_missing)
   1148             # split features and borders go from leafs to the root
   1149             for elem in self.loaded_cb_model['oblivious_trees'][tree_index]['splits']:
-> 1150                 split_features_index.append(elem['float_feature_index'])
   1151                 borders.append(elem['border'])
   1152 

KeyError: 'float_feature_index'
```
This error is [already known](https://github.com/slundberg/shap/issues/662). But I can't get what you've got.

**Comment by annaveronika** [comment]
@sonfiree We suggest to use catboost code to calculate shap values until fix in shap library is done.
Here is an example:
```
shap_values = trained_model.get_feature_importance(Pool(X, y), type='ShapValues')
```

Or you can use one of the previous versions of shap.

**Comment by sonfiree** [comment]
@annaveronika which version is suitable?

**Comment by annaveronika** [comment]
I think 0.29.1 or earlier should work fine.

**Comment by annaveronika** [comment]
This is fixed now by https://github.com/slundberg/shap/pull/736 and will be out in next shap version. For now please use older shap or generate shap values using catboost library.

**Comment by Trollgeir** [comment]
@annaveronika I still get this error with SHAP==0.29.3 and catboost==1.65.5
