### ISSUE TITLE
CatBoostClassifier doesn't work well with sklearn's CalibratedClassifierCV

### ISSUE THREAD

**Issue by zoj613** [catboost/catboost#999]
Problem:
When trying to calibrate the class probability estimates with scikit-learn's `CalibratedClassifierCV`, all I get are 1's for the negative target and 0's for the positive target in a binary classification problem. If I use `CatBoostClassifier` indipendently I get normal looking probabilities. This leads me to believe that this Classifier is not compatible with the calibration technique. Is there a way I can go about fixing this issue?
To reproduce:
```python
from catboost import CatBoostClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.datasets import make_classification

X, y = make_classification(100, 10)

cat = CatBoostClassifier(verbose=0)
calib = CalibratedClassifierCV(base_estimator=cat, method='sigmoid', cv=2)
cat.fit(X, y)
calib.fit(X, y)
print(cat.predict_proba(X))
print(calib.predict_proba(X))
```
catboost version: 0.17.1
Operating System: Ubuntu 18.04.3 LTS
CPU: Intel® Core™ i7-8750H CPU @ 2.20GHz × 12 
GPU: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2

**Comment by zoj613** [comment]
ping @andrey-khropov

**Comment by andrey-khropov** [comment]
This issue has been fixed by commit 0b4a4353887455b1042aa04ccb98226ee8c02097 and released in CatBoost 0.18.

Sorry that I hasn't updated this issue earlier.

**Comment by zoj613** [comment]
@andrey-khropov I dont think the commit solved the issue. In catboost 0.20.1 here is the error I get running the same script above:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-c5f0e0bc2056> in <module>
      8 calib = CalibratedClassifierCV(base_estimator=cat, method='sigmoid', cv=2)
      9 cat.fit(X, y)
---> 10 calib.fit(X, y)
     11 print(cat.predict_proba(X))
     12 print(calib.predict_proba(X))

~/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/sklearn/calibration.py in fit(self, X, y, sample_weight)
    194                                               sample_weight[test])
    195                 else:
--> 196                     calibrated_classifier.fit(X[test], y[test])
    197                 self.calibrated_classifiers_.append(calibrated_classifier)
    198 

~/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/sklearn/calibration.py in fit(self, X, y, sample_weight)
    343         Y = label_binarize(y, self.classes_)
    344 
--> 345         df, idx_pos_class = self._preproc(X)
    346         self.calibrators_ = []
    347 

~/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/sklearn/calibration.py in _preproc(self, X)
    310 
    311         idx_pos_class = self.label_encoder_.\
--> 312             transform(self.base_estimator.classes_)
    313 
    314         return df, idx_pos_class

~/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/sklearn/preprocessing/label.py in transform(self, y)
    255             return np.array([])
    256 
--> 257         _, y = _encode(y, uniques=self.classes_, encode=True)
    258         return y
    259 

~/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/sklearn/preprocessing/label.py in _encode(values, uniques, encode)
    108         return res
    109     else:
--> 110         return _encode_numpy(values, uniques, encode)
    111 
    112 

~/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/sklearn/preprocessing/label.py in _encode_numpy(values, uniques, encode)
     47         if diff:
     48             raise ValueError("y contains previously unseen labels: %s"
---> 49                              % str(diff))
     50         encoded = np.searchsorted(uniques, values)
     51         return uniques, encoded

ValueError: y contains previously unseen labels: ['0', '1']
```

**Comment by andrey-khropov** [comment]
> @andrey-khropov I dont think the commit solved the issue.

Turns out it depends on scikit-learn version. It works for scikit-learn<=0.19.2 but does not work for scikit-learn>=0.20.4.

Ok, we'll fix it for newer scikit-learn versions.

**Comment by zoj613** [comment]
> > @andrey-khropov I dont think the commit solved the issue.
> 
> Turns out it depends on scikit-learn version. Commit [0b4a435](https://github.com/catboost/catboost/commit/0b4a4353887455b1042aa04ccb98226ee8c02097) fixes the issue for scikit-learn<=0.19.2 but does not work for scikit-learn>=0.20.4.
> 
> Ok, we'll fix it for newer scikit-learn versions.

thanks @andrey-khropov

**Comment by zoj613** [comment]
Has it been fixed yet @andrey-khropov

**Comment by andrey-khropov** [comment]
> Has it been fixed yet @andrey-khropov

It has been fixed by commit https://github.com/catboost/catboost/commit/f2d4cc2aa3b9a6421b731dd97634ec2c3191c181, the release with this fix included is expected within a day.

**Comment by chanansh** [comment]
consider bypassing sklearn validation gateway via using the internal class `from sklearn.calibration import _CalibratedClassifier` which will not throw an error at you.

**Comment by zonnalobo** [comment]
This issue should not be closed because CatBoost still cannot work with CalibratedCV Sklearn if cat_features is used.
